services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
